mp.jwt.verify.publickey.location=http://localhost:12345/public.pem
mp.jwt.verify.issuer=https://localhost:12345
gzl.jwt.verify.audience=http://localhost
gzl.sso.url=http://localhost:12345
gzl.m2m.registration.startup.enabled=false
gzl.service.registry.enabled=false
quarkus.datasource.devservices.reuse=false
gzl.root.test.bed.url=http://localhost
gzl.terms.of.service.url=https://www.ihe-europe.net/privacy-policy
gzl.privacy.policy.url=https://www.ihe-europe.net/privacy-policy
gzl.tm.jdbc.password=gazelle
gzl.tm.jdbc.url=jdbc:postgresql://localhost:5433/gazelle
gzl.tm.jdbc.username=gazelle
gzl.tm.url=http://localhost:8082
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/gum
quarkus.datasource.username=gazelle
quarkus.datasource.password=gazelle
# Allow quarkus to listen on all network interfaces (ipv4, ipv6)
quarkus.rest-client.tm-api.url=http://localhost:8082/gazelle/rest
#quarkus.hibernate-orm.schema-management.strategy=drop-and-create
quarkus.mailer.mock=true
quarkus.mailer.host=localhost
quarkus.mailer.tls=false

# Need to add oidc-server indexing to avoid AmbigousResolutionException during ITs
quarkus.index-dependency.m2mserver.group-id=net.ihe.gazelle
quarkus.index-dependency.m2mserver.artifact-id=oidc-server

quarkus.http.test-port=0

#"db/migration" = src/main/resources/db/migration, "classpath:/db/migration" = src/it/resources/db/migration
quarkus.flyway.locations=db/migration,classpath:/db/migration
quarkus.datasource.devservices.volumes."classpath\:./images"=/var/log/images

# Redirect the outgoing.organization-management-out channels to use the in-memory connector for testing
mp.messaging.outgoing.organization-management-out.connector=smallrye-in-memory
mp.messaging.outgoing.organization-management-out.merge=true


# Enable the Hibernate SQL log
#quarkus.hibernate-orm.log.sql=true
#quarkus.log.category."org.hibernate.orm.jdbc.bind".level=TRACE
#quarkus.log.category."org.hibernate.orm.jdbc.extract".level=TRACE
#quarkus.log.category."org.hibernate".level=TRACE
#quarkus.hibernate-orm.log.bind-parameters=true