#!/bin/bash
set -e

: "${DB_HOST:=db}"
: "${DB_PORT:=5432}"
: "${DB_NAME:=gazelle-tm}"
: "${DB_USER:=gazelle}"
: "${DB_PASSWORD:=gazelle}"

# Seed /opt/gazelle volume on first run
if [ ! -d /opt/gazelle/reports ]; then
  echo "[entrypoint] seeding /opt/gazelle from image"
  cp -rn /opt/gazelle-dist/* /opt/gazelle/ || true
fi
# CAS config is rendered from PUBLIC_URL on every boot (single knob in .env)
: "${PUBLIC_URL:=http://gazelle.localhost:8888}"
mkdir -p /opt/gazelle/cas
cat > /opt/gazelle/cas/gazelle-tm.properties <<CASEOF
# Generated by entrypoint.sh from PUBLIC_URL=${PUBLIC_URL} — do not edit (overwritten on boot)
service=${PUBLIC_URL}/tm
casServerUrlPrefix=${PUBLIC_URL}/auth/realms/gazelle/protocol/cas
casServerLoginUrl=${PUBLIC_URL}/auth/realms/gazelle/protocol/cas/login
casLogoutUrl=${PUBLIC_URL}/auth/realms/gazelle/protocol/cas/logout
CASEOF

# Render standalone.xml from template with DB settings
CFG=/usr/local/jboss7/standalone/configuration
sed -e "s|@DB_HOST@|${DB_HOST}|g" \
    -e "s|@DB_PORT@|${DB_PORT}|g" \
    -e "s|@DB_NAME@|${DB_NAME}|g" \
    -e "s|@DB_USER@|${DB_USER}|g" \
    -e "s|@DB_PASSWORD@|${DB_PASSWORD}|g" \
    "${CFG}/standalone.xml.template" > "${CFG}/standalone.xml"

# Behind a reverse proxy JBoss must generate redirect/service URLs with the
# PUBLIC scheme/host/port, not its own (http, container-internal). EAP 6 has no
# X-Forwarded-* support on this connector, so pin them statically.
if [ -n "${PUBLIC_HOST:-}" ]; then
  SECURE=false; [ "${PUBLIC_SCHEME:-http}" = "https" ] && SECURE=true
  sed -i "s|<connector name=\"http\" protocol=\"HTTP/1.1\" scheme=\"http\" socket-binding=\"http\"/>|<connector name=\"http\" protocol=\"HTTP/1.1\" scheme=\"${PUBLIC_SCHEME:-http}\" socket-binding=\"http\" proxy-name=\"${PUBLIC_HOST}\" proxy-port=\"${PUBLIC_PORT:-80}\" secure=\"${SECURE}\"/>|" "${CFG}/standalone.xml"
fi

# SMTP: render the mail session from SMTP_* env (single knob in .env).
# mail:1.1 supports ssl / tls (STARTTLS) attributes and <login> credentials.
if [ -n "${SMTP_HOST:-}" ]; then
  LOGIN=""
  [ -n "${SMTP_USERNAME:-}" ] && LOGIN="<login name=\"${SMTP_USERNAME}\" password=\"${SMTP_PASSWORD:-}\"/>"
  # TM's Seam components.xml looks up the session at java:jboss/mail (not /Default)
  sed -i "s|jndi-name=\"java:jboss/mail/Default\"|jndi-name=\"java:jboss/mail\"|" "${CFG}/standalone.xml"
  sed -i "s|<subsystem xmlns=\"urn:jboss:domain:mail:1.0\">|<subsystem xmlns=\"urn:jboss:domain:mail:1.1\">|" "${CFG}/standalone.xml"
  sed -i "s|<smtp-server outbound-socket-binding-ref=\"mail-smtp\"/>|<smtp-server outbound-socket-binding-ref=\"mail-smtp\" ssl=\"${SMTP_SSL:-false}\" tls=\"${SMTP_STARTTLS:-false}\">${LOGIN}</smtp-server>|" "${CFG}/standalone.xml"
  sed -i "s|<remote-destination host=\"localhost\" port=\"25\"/>|<remote-destination host=\"${SMTP_HOST}\" port=\"${SMTP_PORT:-25}\"/>|" "${CFG}/standalone.xml"
fi
# Trust the bundled fake-SMTP CA (adds to JRE cacerts; harmless for real servers)
if [ -f /opt/smtp-ca/ca.pem ]; then
  keytool -importcert -noprompt -trustcacerts -alias gazelle-smtp-ca \
    -file /opt/smtp-ca/ca.pem -keystore "${JAVA_HOME}/jre/lib/security/cacerts" \
    -storepass changeit >/dev/null 2>&1 || true
fi

# Wait for PostgreSQL
echo "[entrypoint] waiting for ${DB_HOST}:${DB_PORT}"
for i in $(seq 1 120); do
  if (exec 3<>"/dev/tcp/${DB_HOST}/${DB_PORT}") 2>/dev/null; then exec 3>&- 3<&-; break; fi
  sleep 2
done

# Clear stale deployment markers so the scanner redeploys on restart
rm -f /usr/local/jboss7/standalone/deployments/gazelle-tm.ear.{failed,undeployed,pending} 2>/dev/null || true

# Keycloak+NextAuth cookies on the shared domain can exceed JBossWeb's default
# 8k header limit -> HTTP 400 on /tm; raise it to match nginx (32k)
export JAVA_OPTS="-server ${JAVA_OPTS_EXTRA:- -Xms512m -Xmx2048m -XX:MaxPermSize=768m -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8} -Djava.awt.headless=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.security.egd=file:/dev/./urandom -Dorg.apache.coyote.http11.Http11Protocol.MAX_HEADER_SIZE=32768"

echo "[entrypoint] starting JBoss"
exec /usr/local/jboss7/bin/standalone.sh -b 0.0.0.0 -bmanagement 0.0.0.0
