
#Metadata

gzl.service.name=${quarkus.application.name}



gzl.service.validation.name=${gzl.service.name}

gzl.xmlvalidator.profile.index.path=${XML_VALIDATION_INDEX_PATH:/opt/xml-validation-service-resources/index.json}
gzl.xmlvalidator.tabprofiles.path=${XML_VALIDATION_TABPROFILES_PATH:/opt/xml-validation-service-resources/TABProfilesConfiguration.json}
gzl.migration.enabled=${GZL_MIGRATION_ENABLED:true}
gzl.service.rest.interface.baseUrl=http://localhost:${quarkus.http.port}${quarkus.http.root-path}/rest
phschematron.version=${phschematron.version}

# Quarkus properties
quarkus.swagger-ui.always-include=true
quarkus.http.root-path=/xml-validation-service
quarkus.swagger-ui.path=/${quarkus.application.name}/swagger-ui
quarkus.smallrye-metrics.path=/metrics
quarkus.http.port=8084
quarkus.log.level=INFO

# service registry
gzl.service.registry.enabled=${GZL_SERVICE_REGISTRY_ENABLED:false}
gzl.service.registry.url=${GZL_SERVICE_REGISTRY_URL:http://localhost:8089/service-registry}

# m2m / sso
gzl.sso.admin.user=${GZL_SSO_ADMIN_USER:gazelle-clients-admin}
gzl.sso.admin.password=${GZL_SSO_ADMIN_PASSWORD:gazelle}
gzl.sso.url=${GZL_SSO_URL:http://localhost:8631/auth}
gzl.m2m.client.secret=${GZL_M2M_CLIENT_SECRET:kROmcsJdoDinVHEwq0kLKipXrMcmU9H0}
gzl.service.k8s.id=${GZL_SERVICE_K8S_ID:xml-validator-1200989-002}

# other
