/*
 * Copyright 2025-2026 IHE International.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.ihe.gazelle.maestro.itb.step.business;

import net.ihe.gazelle.maestro.api.business.property.ByteArrayProperty;
import net.ihe.gazelle.maestro.api.business.property.Property;
import net.ihe.gazelle.maestro.api.business.property.StringProperty;
import net.ihe.gazelle.maestro.api.business.test.SupportedInput;
import net.ihe.gazelle.maestro.api.business.test.SupportedTextInput;
import net.ihe.gazelle.maestro.spi.business.StepDefinition;

import java.io.Serial;
import java.util.List;
import java.util.Map;

/**
 * An ITB Step is an automated step used to execute a test in ITB. This step has 7 properties.
 */
public class ItbStepDefinition implements StepDefinition {

   /**
    * Represents the type identifier for an ITB (Integration Test Bed) step definition.
    */
   public static final String TYPE = "ITB";

   // Inputs
   /**
    * Identifier of the test case to be executed in the ITB (Integration Test Bed) step.
    */
   public static final String TEST_CASE = "testCase";

   /**
    * Represents the identifier of the actor in the Integration Test Bed (ITB) step.
    */
   public static final String ACTOR_ID = "actorID";
   /**
    * Execution mode for ITB step: ASYNC (default) or SYNC.
    */
   public static final String EXECUTION_MODE = "executionMode";
   /**
    * ITB payload mapping mode: FLAT (default) or USER_INPUT_MAP.
    */
   public static final String ITB_PAYLOAD_MODE = "itbPayloadMode";

   // outputs
   /**
    * Represents the key for the XML report output generated by the ITB step.
    */
   public static final String XML_REPORT = "xmlReport";

   /**
    * Represents the key for the PDF report output generated by the ITB (Integration Test Bed) step.
    */
   public static final String PDF_REPORT = "pdfReport";

   /**
    * Represents the key for the logs output generated during the execution of an ITB (Integration Test Bed) step.
    */
   public static final String LOGS = "logs";

   @Serial
   private static final long serialVersionUID = 4790241684818825787L;

   /**
    * Default constructor.
    */
   public ItbStepDefinition() {
      // Empty
   }

   @Override
   public String getType() {
      return TYPE;
   }

   @Override
   public List<SupportedInput> getSupportedInputs() {
      return List.of(
            new SupportedTextInput().setId(TEST_CASE).setLabel("Test Case").setRequired(true),
            new SupportedTextInput().setId(ACTOR_ID).setLabel("Actor ID").setRequired(true),
            new SupportedTextInput().setId(EXECUTION_MODE).setLabel("Execution Mode").setRequired(false),
            new SupportedTextInput().setId(ITB_PAYLOAD_MODE).setLabel("ITB Payload Mode").setRequired(false)
      );
   }

   @Override
   public Map<String, Class<? extends Property>> getOutputsDefinition() {
      return Map.of(
            XML_REPORT, ByteArrayProperty.class,
            PDF_REPORT, ByteArrayProperty.class,
            LOGS, StringProperty.class
      );
   }

}
