#
# Copyright 2025-2026 IHE International.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

quarkus.http.test-port=0
gzl.it-port=34400

# Service definition and registration
gzl.service.registry.enabled=false
gzl.service.registry.url=http://localhost:34400/service-registry

# SSO configurations
gzl.m2m.registration.startup.enabled=false
gzl.sso.url=http://localhost:12345
gzl.sso.admin.user=admin
gzl.sso.admin.password=password
gzl.jwt.verify.audience=http://localhost
mp.jwt.verify.issuer=https://localhost:12345
mp.jwt.verify.publickey.location=http://localhost:12345/public.pem

gzl.svs.url=http://localhost:${gzl.it-port}/SVSSimulator/rest
gzl.simulation.gateway.services.cache.timeout.minutes=1
gzl.simulation.gateway.sequences.cache.max.timeout.minutes=10