<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.ihe.gazelle</groupId>
        <artifactId>gazelle-user-management</artifactId>
        <version>5.0.1</version>
    </parent>
    <packaging>pom</packaging>
    <artifactId>gazelle-keycloak</artifactId>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <!-- Quarkus version used by Keycloak 26.6.4 -->
        <quarkus.platform.version>3.33.2.1</quarkus.platform.version>
        <keycloak.version>26.6.4</keycloak.version>
    </properties>

    <modules>
        <module>keycloak-core</module>
        <module>keycloak-provider</module>
        <module>keycloak-theme</module>
    </modules>

    <dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>io.quarkus.platform</groupId>
            <artifactId>quarkus-bom</artifactId>
            <version>${quarkus.platform.version}</version>
            <!-- Excluding keycloak dependencies from quarkus-bom because there are in version 21.X.X -->
            <exclusions>
                <exclusion>
                    <groupId>org.keycloak</groupId>
                    <artifactId>keycloak-common</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>org.keycloak</groupId>
                    <artifactId>keycloak-core</artifactId>
                </exclusion>
            </exclusions>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak.bom</groupId>
            <artifactId>keycloak-spi-bom</artifactId>
            <version>${keycloak.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-model-storage</artifactId>
            <version>${keycloak.version}</version>
            <type>pom</type>
            <scope>import</scope>
        </dependency>
    </dependencies>
    </dependencyManagement>
</project>