# Root context
quarkus.http.port=8081
quarkus.http.root-path=/gum
gzl.service.k8s.id=user-management-f187100000-001
root.test.bed.url=http://localhost:${quarkus.http.port}

# Jackson configurations
quarkus.jackson.serialization-inclusion=non-null

# Swagger UI configurations
quarkus.smallrye-health.root-path=${quarkus.http.root-path}/health
quarkus.swagger-ui.title=GUM API
quarkus.smallrye-openapi.servers=${root.test.bed.url}${quarkus.http.root-path}

# Datasource configurations
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_GUM_USER}
quarkus.datasource.password=${DB_GUM_PASSWORD}
quarkus.datasource.jdbc.url=${DB_GUM_JDBC_URL:jdbc:postgresql://${DB_GUM_HOST}:${DB_GUM_PORT}/${DB_GUM_NAME}}
quarkus.datasource.jdbc.max-size=16

# Hibernate configurations
quarkus.hibernate-orm.schema-management.strategy=none

# Flyway configurations
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=gum

# Mail configurations
quarkus.mailer.from=no-reply@${SMTP_FROM_DOMAIN:${FQDN}}
quarkus.mailer.host=${SMTP_HOST}
quarkus.mailer.port=${SMTP_PORT}
quarkus.mailer.tls=${SMTP_SSL_ENABLED}
quarkus.mailer.username=${SMTP_USERNAME}
quarkus.mailer.password=${SMTP_PASSWORD}
quarkus.mailer.mock=${SMTP_MOCK_ENABLED}

# Dev services
quarkus.devservices.enabled=true
quarkus.datasource.devservices.enabled=true
quarkus.datasource.devservices.port=5433
quarkus.datasource.devservices.db-name=gum
quarkus.datasource.devservices.image-name=postgres:14
quarkus.datasource.devservices.username=gazelle
quarkus.datasource.devservices.password=gazelle


# broker config (production)
mqtt.host=${MQTT_HOST:localhost}
mqtt.port=${MQTT_PORT:1883}
mqtt.username=${MQTT_USERNAME:gazelle}
mqtt.password=${MQTT_PASSWORD:gazelle}
mqtt.reconnect-interval-seconds=30

# MQTT configurations
mp.messaging.outgoing.organization-management-out.connector=smallrye-mqtt
mp.messaging.outgoing.organization-management-out.topic=organization-management
mp.messaging.outgoing.organization-management-out.qos=1
mp.messaging.outgoing.organization-management-out.auto-clean-session=false
mp.messaging.outgoing.organization-management-out.host=${mqtt.host}
mp.messaging.outgoing.organization-management-out.port=${mqtt.port}
mp.messaging.outgoing.organization-management-out.username=${mqtt.username}
mp.messaging.outgoing.organization-management-out.password=${mqtt.password}
mp.messaging.outgoing.organization-management-out.client-id=${gzl.service.k8s.id}-organization-management-out
mp.messaging.outgoing.organization-management-out.reconnect-interval-seconds=${mqtt.reconnect-interval-seconds}
mp.messaging.outgoing.organization-management-out.retain=true

# Required to resolve implementations for CDI
quarkus.index-dependency.core.group-id=net.ihe.gazelle
quarkus.index-dependency.core.artifact-id=user-management-core
quarkus.index-dependency.commons.group-id=net.ihe.gazelle
quarkus.index-dependency.commons.artifact-id=user-management-commons
quarkus.index-dependency.security.group-id=net.ihe.gazelle
quarkus.index-dependency.security.artifact-id=security

# GZL properties
gzl.m2m.registration.startup.enabled=${GZL_M2M_REGISTRATION_STARTUP_ENABLED:true}
gzl.organization.creation.enabled=${GZL_ORGANIZATION_CREATION_ENABLED}
gzl.root.test.bed.url=${ROOT_TEST_BED_URL}
gzl.jwt.verify.audience=${GZL_JWT_VERIFY_AUDIENCE}
gzl.service.name=gazelle-user-management
gzl.service.version=${quarkus.application.version}
gzl.sso.realm.name=${GZL_SSO_REALM:gazelle}
gzl.sso.url=${GZL_SSO_URL}
gzl.terms.of.service.url=${GZL_TERMS_OF_SERVICE_URL}
gzl.privacy.policy.url=${GZL_PRIVACY_POLICY_URL}
gzl.tm.jdbc.password=${DB_TM_PASSWORD}
gzl.tm.jdbc.url=${DB_TM_JDBC_URL:jdbc:postgresql://${DB_TM_HOST}:${DB_TM_PORT}/${DB_TM_NAME}}
gzl.tm.jdbc.username=${DB_TM_USER}
gzl.tm.url=${GZL_TM_URL}
gzl.user.management.front.url=${GZL_USER_MANAGEMENT_FRONT_URL}
gzl.user.inactivated.purge.after.days=${GZL_USER_INACTIVATED_PURGE_AFTER_DAYS:31}
gzl.user.registration.enabled=${GZL_USER_REGISTRATION_ENABLED}
gzl.user.creation.email.notification.enabled=${GZL_USER_CREATION_EMAIL_NOTIFICATION_ENABLED:true}
