#
# Copyright 2025-2026 IHE International.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

quarkus.http.port=8087
quarkus.http.root-path=/simulation-gateway
quarkus.rest.path=/rest

# Open API configuration
quarkus.smallrye-health.root-path=${quarkus.http.root-path}/health
quarkus.smallrye-openapi.always-run-filter=true
quarkus.smallrye-openapi.info-version=${quarkus.application.version}
quarkus.smallrye-openapi.path=${quarkus.http.root-path}${quarkus.rest.path}/openapi
quarkus.smallrye-openapi.security-scheme=oauth2-implicit
quarkus.smallrye-openapi.security-scheme-name=Keycloak

# Swagger UI configurations
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.default-models-expand-depth=-1
quarkus.swagger-ui.path=${quarkus.http.root-path}/swagger-ui
quarkus.swagger-ui.title=Simulation API UI
quarkus.swagger-ui.theme=original
quarkus.swagger-ui.oauth-client-id=OIDC_GAZELLE_CLIENT
quarkus.swagger-ui.oauth2-redirect-url=${quarkus.http.application-root-path}${quarkus.http.root-path}/swagger-ui/oauth2-redirect.html
quarkus.swagger-ui.persist-authorization=true

# SSO configurations
gzl.m2m.registration.startup.enabled=true
gzl.m2m.client.secret=secret
gzl.sso.url=http://localhost/auth
gzl.sso.realm=gazelle
gzl.sso.admin.user=gazelle-clients-admin
gzl.sso.admin.password=gazelle
gzl.jwt.verify.audience=http://localhost
mp.jwt.verify.issuer=${gzl.sso.url}/realms/${gzl.sso.realm}
mp.jwt.verify.publickey.location=${gzl.sso.url}/realms/${gzl.sso.realm}/protocol/openid-connect/certs

# Gazelle
gzl.terms.of.service.url=https://www.ihe-europe.net/privacy-policy
gzl.service.registry.url=http://localhost:8088/service-registry
#gzl.svs.url=${GZL_SVS_URL:http://localhost:8601/SVSSimulator/rest}
gzl.svs.url=https://preprod.ihe-europe.net/SVSSimulator/rest
gzl.service.registry.enabled=true
gzl.service.name=Simulation Gateway
gzl.service.version=${quarkus.application.version}
gzl.service.k8s.id=simulation-gateway-263753-001
gzl.simulation.gateway.services.cache.timeout.minutes=5
gzl.simulation.gateway.sequences.cache.max.timeout.minutes=720

# Tests
quarkus.http.test-port=0
%test.gzl.it-port=34400
%test.gzl.service.registry.url=http://localhost:${%test.gzl.it-port}
%test.gzl.svs.url=http://localhost:${%test.gzl.it-port}/SVSSimulator/rest
%test.gzl.service.registry.enabled=false
%test.gzl.m2m.registration.startup.enabled=false
%test.gzl.simulation.gateway.services.cache.timeout.minutes=1
%test.gzl.simulation.gateway.sequences.cache.max.timeout.minutes=10