quarkus.datasource.gum-store.db-kind=postgresql
quarkus.datasource.gum-store.username=${DB_GUM_USER}
quarkus.datasource.gum-store.password=${DB_GUM_PASSWORD}
quarkus.datasource.gum-store.jdbc.url=${DB_GUM_JDBC_URL:jdbc:postgresql://${DB_GUM_HOST}:${DB_GUM_PORT}/${DB_GUM_NAME}}
quarkus.datasource.gum-store.jdbc.transactions=xa