/*
 * Copyright 2026 IHE International.
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package net.ihe.gazelle.maestro.api.business.testreport;

import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;

class TestReportBuilderTest {

    @Test
    void shouldBuildTestReportAndComputeCounters() {
        Instant timestamp = Instant.parse("2025-01-01T00:00:00Z");

        StepRunReportBuilder stepRunReportBuilder = new StepRunReportBuilder()
                .setStepName("Validation step")
                .setType("VALIDATION")
                .setResult(StepResult.PASSED);

        TestRunReportBuilder testRunReportBuilder = new TestRunReportBuilder()
                .setDateTime(timestamp)
                .setTest(new TestBuilder()
                        .setId("test-1")
                        .setName("Sample test"))
                .addStepRunReport(stepRunReportBuilder);

        TestReportBuilder builder = new TestReportBuilder()
                .setReportVersion()
                .setDateTime(timestamp)
                .setTestService(new TestServiceBuilder()
                        .setServiceIdentification(new EntityIdentificationBuilder()
                                .setName("Gazelle")
                                .setVersion("1.0"))
                        .setDisclaimer("Generated by Gazelle"))
                .addSystemUnderTest(new SystemUnderTestBuilder()
                        .setSystemIdentification(new EntityIdentificationBuilder()
                                .setName("sut-1")
                                .setVersion("2025")))
                .setTestSuiteName("MAESTRO-SUITE")
                .setNote("Sample test report")
                .setUrlToTestSuiteResult("http://example.test/reports/1")
                .addTestRunReport(testRunReportBuilder);

        TestReport report = builder.build();

        assertEquals(TestReport.REPORT_VERSION, report.getReportVersion());
        assertEquals(timestamp, report.getDateTime());
        assertEquals("MAESTRO-SUITE", report.getTestSuiteName());
        assertEquals("Sample test report", report.getNote());
        assertEquals("http://example.test/reports/1", report.getUrlToTestSuiteResult());

        assertEquals("Gazelle", report.getTestService().getServiceIdentification().getName());
        assertEquals("sut-1", report.getSystemsUnderTest().getFirst().getSystemIdentification().getName());

        assertEquals(1, report.getTestRunReports().size());
        assertEquals(Result.PASSED, report.getResult());

        TestCounters counters = report.getTestCounters();
        assertNotNull(counters);
        assertEquals(1, counters.getTotal());
        assertEquals(1, counters.getPassed());
        assertEquals(0, counters.getFailed());
        assertEquals(0, counters.getUndefined());
    }
}
