services:
  simulation-mocks:
    container_name: simulation-mocks
    image: ${REGISTRY_APP}/${REGISTRY_PATH}/simulation-mocks:${APP_VERSION}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      # - "/var/logs/gazelle-test-execution:/deployments/logs:rw" TOFIX : permission denied to write to /var/logs/
    env_file:
      - ${GZL_COMPOSE_ENV_FILE:-.env.dev}
    restart: always
    network_mode: "host"
    logging:
      options:
        max-size: "${MAX_SIZE}"
        max-file: "${MAX_FILE}"
    mem_reservation: ${MEM_RESERVATION}
    mem_limit: ${MEM_LIMIT}

  simulation-gateway:
    container_name: simulation-gateway
    image: ${REGISTRY_APP}/${REGISTRY_PATH}/simulation-gateway:${APP_VERSION}
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
      # - "/var/logs/gazelle-test-execution:/deployments/logs:rw" TOFIX : permission denied to write to /var/logs/
    env_file:
      - ${GZL_COMPOSE_ENV_FILE:-.env.dev}
    restart: always
    network_mode: "host"
    logging:
      options:
        max-size: "${MAX_SIZE}"
        max-file: "${MAX_FILE}"
    mem_reservation: ${MEM_RESERVATION}
    mem_limit: ${MEM_LIMIT}
    depends_on:
      simulation-mocks:
        condition: service_healthy
