<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>net.ihe.gazelle</groupId>
        <artifactId>gazelle-keycloak</artifactId>
        <version>5.0.1</version>
    </parent>

    <artifactId>keycloak-core</artifactId>

    <properties>
        <sonar.coverage.exclusions>**/interlay/**</sonar.coverage.exclusions>
        <embedded-postgres.version>1.3.1</embedded-postgres.version>
        <mybatis.version>3.5.9</mybatis.version>
        <paho.mqtt.version>1.2.5</paho.mqtt.version>
    </properties>

    <build>
        <finalName>${project.artifactId}</finalName>
        <resources>
            <resource>
                <directory>src/it/resources</directory>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <environmentVariables>
                        <GZL_SSO_REALM>gazelle</GZL_SSO_REALM>
                        <GZL_SSO_URL>http://localhost:8080</GZL_SSO_URL>
                        <GZL_M2M_CLIENT_SECRET>secret</GZL_M2M_CLIENT_SECRET>
                        <GZL_SSO_ADMIN_USER>test</GZL_SSO_ADMIN_USER>
                        <GZL_SSO_ADMIN_PASSWORD>test</GZL_SSO_ADMIN_PASSWORD>
                        <GZL_GUM_K8S_ID>gazelle-user-management-12345-45678</GZL_GUM_K8S_ID>
                        <GZL_SERVICE_NAME>gazelle-user-management</GZL_SERVICE_NAME>
                    </environmentVariables>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.pitest</groupId>
                <artifactId>pitest-maven</artifactId>
                <configuration>
                    <!-- Exclude some classes where environment variables are required -->
                    <excludedClasses>
                        <param>net.ihe.gazelle.keycloak.core.interlay.configuration.ApplicationConfigImpl</param>
                        <param>net.ihe.gazelle.keycloak.core.interlay.configuration.DatabaseConfigImpl</param>
                    </excludedClasses>
                    <excludedTestClasses>
                        <param>net.ihe.gazelle.keycloak.core.interlay.configuration.ConfigurationTest</param>
                        <param>net.ihe.gazelle.keycloak.core.interlay.dao.datasource.GazelleDataSourcesTest</param>
                    </excludedTestClasses>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>test-jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>


    <dependencies>
        <!-- Gazelle dependencies -->
        <dependency>
            <groupId>net.ihe.gazelle</groupId>
            <artifactId>user-management-api</artifactId>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>net.ihe.gazelle</groupId>
            <artifactId>user-management-commons</artifactId>
        </dependency>
        <dependency>
            <groupId>net.ihe.gazelle</groupId>
            <artifactId>security</artifactId>
        </dependency>

        <!-- Required dep for security -->
        <dependency>
            <groupId>net.ihe.gazelle</groupId>
            <artifactId>lang</artifactId>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
        </dependency>

        <!-- json dependencies -->
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20240205</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.paho</groupId>
            <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
            <version>${paho.mqtt.version}</version>
        </dependency>


        <!-- Import test classes from user-management-commons -->
        <dependency>
            <groupId>net.ihe.gazelle</groupId>
            <artifactId>user-management-commons</artifactId>
            <version>${project.version}</version>
            <type>test-jar</type>
            <scope>test</scope>
        </dependency>

        <!-- simple logger for tests -->
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <scope>test</scope>
        </dependency>

        <!-- junit5 dependencies -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
        </dependency>
        <!-- Mockito dependencies -->
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-inline</artifactId>
        </dependency>
        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-junit-jupiter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
        </dependency>

        <!-- for JDBC testing -->
        <dependency>
            <groupId>io.zonky.test</groupId>
            <artifactId>embedded-postgres</artifactId>
            <version>${embedded-postgres.version}</version>
            <scope>test</scope>
        </dependency>
        <!-- JDBC driver -->
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.mybatis</groupId>
            <artifactId>mybatis</artifactId>
            <version>${mybatis.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>nl.jqno.equalsverifier</groupId>
            <artifactId>equalsverifier</artifactId>
        </dependency>

        <!-- agroal is provided for Keycloak 17+ -->
        <dependency>
            <groupId>io.agroal</groupId>
            <artifactId>agroal-pool</artifactId>
            <scope>provided</scope>
        </dependency>
        <!-- caffeine is provided for Keycloak 17+ -->
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Keycloak dependencies -->
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-server-spi</artifactId>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.keycloak</groupId>
            <artifactId>keycloak-model-storage</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Test dependencies -->
        <dependency>
            <groupId>org.testcontainers</groupId>
            <artifactId>junit-jupiter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.wiremock</groupId>
            <artifactId>wiremock</artifactId>
            <version>${wiremock.version}</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>