<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>net.ihe.gazelle</groupId>
        <artifactId>factory-bom-jdk25-quarkus-3-33</artifactId>
        <version>1.2.2</version>
    </parent>

    <artifactId>gazelle-user-management</artifactId>
    <version>5.0.1</version>
    <packaging>pom</packaging>

    <modules>
        <module>user-management</module>
        <module>gazelle-keycloak</module>
    </modules>

    <scm>
        <connection>scm:git:${git.project.url}</connection>
        <developerConnection>scm:git:${git.project.url}</developerConnection>
        <url>https://gitlab.inria.fr/gazelle/public/core/user-management</url>
        <tag>5.0.1</tag>
    </scm>


    <properties>
        <git.project.url>
            https://${git.user.name}:${git.user.token}@gitlab.inria.fr/gazelle/public/core/user-management.git
        </git.project.url>

        <docker-maven-plugin.version>0.48.1</docker-maven-plugin.version>
        <slf4j.version>2.0.6</slf4j.version>
        <equalsverifier.version>3.16.1</equalsverifier.version>
        <framework.version>4.1.1</framework.version>
        <lang.version>3.0.0</lang.version>
        <failsafe.useModulePath>false</failsafe.useModulePath>
        <assertj-core.version>3.24.2</assertj-core.version>
        <mockito.version>4.8.1</mockito.version>
        <mockserver.version>5.15.0</mockserver.version>
        <docker.image.tag>${project.version}</docker.image.tag>
        <docker.registry.path>rg.fr-par.scw.cloud/gazelle-snapshot/app</docker.registry.path>

        <!-- Runtime config for docker-maven-plugin -->
        <db.ext.port>5433</db.ext.port>
        <db.ext.name>gum</db.ext.name>
        <db.ext.username>gazelle</db.ext.username>
        <db.ext.password>gazelle</db.ext.password>
        <db.ext.host>localhost</db.ext.host>

        <!-- Integration Tests -->
        <it.base.uri>http://localhost</it.base.uri>
        <it.base.port>8082</it.base.port>
        <it.consumer.timeout>600000</it.consumer.timeout>
        <wiremock.version>3.8.0</wiremock.version>

        <skipITs>${skipTests}</skipITs>
        <skipUnitTests>${skipTests}</skipUnitTests>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!-- Import parent BOM for Quarkus and Java configuration -->
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>factory-bom-jdk25-quarkus-3-33</artifactId>
                <version>1.2.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- Gazelle-user management sub-module dependencies -->
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>user-management</artifactId>
                <version>5.0.1</version>
            </dependency>
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>user-management-api</artifactId>
                <version>5.0.1</version>
            </dependency>
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>user-management-client</artifactId>
                <version>5.0.1</version>
            </dependency>
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>user-management-commons</artifactId>
                <version>5.0.1</version>
            </dependency>
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>user-management-core</artifactId>
                <version>5.0.1</version>
            </dependency>
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>user-management-quarkus</artifactId>
                <version>5.0.1</version>
            </dependency>

            <!-- Gazelle-keycloak sub-module dependencies -->
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>gazelle-keycloak</artifactId>
                <version>5.0.1</version>
            </dependency>
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>keycloak-theme</artifactId>
                <version>5.0.1</version>
            </dependency>
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>keycloak-provider</artifactId>
                <version>5.0.1</version>
            </dependency>
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>keycloak-core</artifactId>
                <version>5.0.1</version>
            </dependency>

            <!-- Gazelle dependencies -->
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>framework</artifactId>
                <version>${framework.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>lang</artifactId>
                <version>${lang.version}</version>
            </dependency>

            <!-- Test dependencies -->
            <dependency>
                <groupId>net.ihe.gazelle</groupId>
                <artifactId>security-mocks</artifactId>
                <version>${framework.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.junit.jupiter</groupId>
                <artifactId>junit-jupiter</artifactId>
                <version>5.9.1</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-core</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-inline</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>nl.jqno.equalsverifier</groupId>
                <artifactId>equalsverifier</artifactId>
                <version>${equalsverifier.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.mockito</groupId>
                <artifactId>mockito-junit-jupiter</artifactId>
                <version>${mockito.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.assertj</groupId>
                <artifactId>assertj-core</artifactId>
                <version>${assertj-core.version}</version>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-simple</artifactId>
                <version>${slf4j.version}</version>
                <scope>test</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <!-- Configure some variable environments for unit tests-->
                    <environmentVariables>
                        <DB_TM_USER>testDBUser</DB_TM_USER>
                        <DB_TM_PASSWORD>testDBPassword</DB_TM_PASSWORD>
                        <DB_GUM_USER>gazelle</DB_GUM_USER>
                        <DB_GUM_PASSWORD>gazelle</DB_GUM_PASSWORD>
                        <GZL_TM_URL>https://fakeurl.fr/gazelle</GZL_TM_URL>
                        <ROOT_TEST_BED_URL>http://localhost:8081</ROOT_TEST_BED_URL>
                        <KC_HOSTNAME>http://localhost:28080</KC_HOSTNAME>
                        <GZL_SSO_REALM>gazelle</GZL_SSO_REALM>
                        <GZL_USER_INACTIVATED_PURGE_AFTER_DAYS>31</GZL_USER_INACTIVATED_PURGE_AFTER_DAYS>
                    </environmentVariables>
                </configuration>

            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <configuration>
                    <tagNameFormat>@{project.version}</tagNameFormat>
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <releaseProfiles>release</releaseProfiles>
                </configuration>
            </plugin>
        </plugins>
        <pluginManagement>
            <plugins>
                <plugin>
                    <!-- build gazelle-user-management docker image at maven package phase, and start the container for integration-tests -->
                    <!-- In section plugin-management, because only activated with profile dev -->
                    <groupId>io.fabric8</groupId>
                    <artifactId>docker-maven-plugin</artifactId>
                    <version>${docker-maven-plugin.version}</version>
                    <configuration>
                        <autoCreateCustomNetworks>true</autoCreateCustomNetworks>
                        <images>
                            <!-- DATABASE deployment configuration -->
                            <image>
                                <name>rg.fr-par.scw.cloud/gazelle/app/gazelle-database:17.0.0</name>
                                <alias>gazelle-database</alias>
                                <run>
                                    <containerNamePattern>it-gazelle-database</containerNamePattern>
                                    <network>
                                        <mode>custom</mode>
                                        <name>localit</name>
                                        <alias>gazelle-database</alias>
                                    </network>
                                    <ports>
                                        <port>${db.ext.port}:5433</port>
                                    </ports>
                                    <user>root</user>
                                    <volumes>
                                        <bind>
                                            <volume>src/it/resources:/common-resources/gum</volume>
                                        </bind>
                                    </volumes>
                                    <wait>
                                        <healthy>true</healthy>
                                        <time>10000</time>
                                        <exec>
                                            <postStart>/common-resources/gum/postgres/init_gazelle.sh</postStart>
                                        </exec>
                                    </wait>
                                    <env>
                                        <PGPORT>5433</PGPORT>
                                        <POSTGRES_PASSWORD>${db.ext.password}</POSTGRES_PASSWORD>
                                        <POSTGRES_USER>${db.ext.username}</POSTGRES_USER>
                                        <POSTGRES_BIND>0.0.0.0</POSTGRES_BIND>
                                        <POSTGRES_DB>${db.ext.name}</POSTGRES_DB>
                                    </env>
                                </run>
                            </image>
                            <!-- GUM-keycloak deployment configuration -->
                            <image>
                                <name>${docker.registry.path}/gazelle-user-management-keycloak:${docker.image.tag}</name>
                                <alias>gazelle-user-management-keycloak</alias>
                                <build>
                                    <dockerFile>${project.basedir}/Dockerfile</dockerFile>
                                </build>
                                <run>
                                    <containerNamePattern>it-gazelle-user-management-keycloak</containerNamePattern>
                                    <dependsOn>
                                        <image>gazelle-database</image>
                                    </dependsOn>
                                    <network>
                                        <mode>custom</mode>
                                        <name>localit</name>
                                        <alias>gazelle-user-management-keycloak</alias>
                                    </network>
                                    <ports>
                                        <port>28080:28080</port>
                                        <port>9000:9000</port>
                                        <port>18787:18787</port>
                                    </ports>
                                    <env>
                                        <DB_TM_HOST>gazelle-database</DB_TM_HOST>
                                        <DB_TM_PORT>${db.ext.port}</DB_TM_PORT>
                                        <DB_TM_USER>gazelle</DB_TM_USER>
                                        <DB_TM_PASSWORD>gazelle</DB_TM_PASSWORD>
                                        <DB_TM_NAME>gazelle</DB_TM_NAME>
                                        <DB_KC_HOST>gazelle-database</DB_KC_HOST>
                                        <DB_KC_PORT>${db.ext.port}</DB_KC_PORT>
                                        <DB_KC_USER>gazelle</DB_KC_USER>
                                        <DB_KC_PASSWORD>gazelle</DB_KC_PASSWORD>
                                        <DB_KC_NAME>keycloak</DB_KC_NAME>
                                        <DB_GUM_HOST>gazelle-database</DB_GUM_HOST>
                                        <DB_GUM_PORT>${db.ext.port}</DB_GUM_PORT>
                                        <DB_GUM_USER>gazelle</DB_GUM_USER>
                                        <DB_GUM_PASSWORD>gazelle</DB_GUM_PASSWORD>
                                        <DB_GUM_NAME>${db.ext.name}</DB_GUM_NAME>
                                        <DEBUG>true</DEBUG>
                                        <DEV_MODE>true</DEV_MODE>
                                        <DEBUG_PORT>18787</DEBUG_PORT>
                                        <APP_VERSION>${project.version}</APP_VERSION>
                                        <SCHEMA>http</SCHEMA>
                                        <FQDN>localhost</FQDN>
                                        <GZL_TM_URL>http://localhost:8080/gazelle</GZL_TM_URL>
                                        <GZL_USER_MANAGEMENT_FRONT_URL>http://localhost:3000/gazelle/user-management</GZL_USER_MANAGEMENT_FRONT_URL>
                                        <KC_BOOTSTRAP_ADMIN_USERNAME>admin</KC_BOOTSTRAP_ADMIN_USERNAME>
                                        <KC_BOOTSTRAP_ADMIN_PASSWORD>admin</KC_BOOTSTRAP_ADMIN_PASSWORD>
                                        <GZL_M2M_CLIENT_SECRET>secret</GZL_M2M_CLIENT_SECRET>
                                        <GZL_SSO_URL>http://gazelle-user-management-keycloak:28080</GZL_SSO_URL>
                                        <GZL_GUM_K8S_ID>gazelle-user-management-11111-11111</GZL_GUM_K8S_ID>
                                        <GZL_SSO_ADMIN_USER>gazelle-clients-admin</GZL_SSO_ADMIN_USER>
                                        <GZL_SSO_ADMIN_PASSWORD>gazelle</GZL_SSO_ADMIN_PASSWORD>
                                        <GZL_SSO_ADMIN_EMAIL>clientadmin@test.com</GZL_SSO_ADMIN_EMAIL>
                                        <GZL_USER_INACTIVATED_PURGE_AFTER_DAYS>31</GZL_USER_INACTIVATED_PURGE_AFTER_DAYS>
                                        <KC_HTTP_PORT>28080</KC_HTTP_PORT>
                                        <KC_HTTP_HOST>0.0.0.0</KC_HTTP_HOST>
                                        <KC_HTTP_MANAGEMENT_PORT>9000</KC_HTTP_MANAGEMENT_PORT>
                                        <KC_HTTP_ENABLED>true</KC_HTTP_ENABLED>
                                        <KC_HOSTNAME>http://localhost:28080</KC_HOSTNAME>
                                        <KC_HOSTNAME_STRICT>false</KC_HOSTNAME_STRICT>
                                        <GZL_SSO_REALM>gazelle</GZL_SSO_REALM>
                                        <ROOT_TEST_BED_URL>http://localhost:8080</ROOT_TEST_BED_URL>
                                        <SMTP_USERNAME>test</SMTP_USERNAME>
                                        <SMTP_PASSWORD>test</SMTP_PASSWORD>
                                        <SMTP_PORT>1025</SMTP_PORT>
                                        <SMTP_HOST>mailhog</SMTP_HOST>
                                        <GZL_SERVICE_NAME>gazelle-user-management</GZL_SERVICE_NAME>
                                        <GZL_TERMS_OF_SERVICE_URL>https://termslink.fr</GZL_TERMS_OF_SERVICE_URL>
                                        <GZL_PRIVACY_POLICY_URL>https://privacypolicy.fr</GZL_PRIVACY_POLICY_URL>
                                        <MQTT_HOST>mosquitto</MQTT_HOST>
                                        <MQTT_PORT>1884</MQTT_PORT>
                                        <MQTT_USERNAME>it_user</MQTT_USERNAME>
                                        <MQTT_PASSWORD>it_password</MQTT_PASSWORD>
                                    </env>
                                    <wait>
                                        <healthy>true</healthy>
                                        <time>300000</time>
                                    </wait>
                                </run>
                            </image>
                            <!-- GUM-quarkus deployment configuration -->
                            <image>
                                <name>${docker.registry.path}/gazelle-user-management-quarkus:${docker.image.tag}</name>
                                <alias>gazelle-user-management-quarkus</alias>
                                <run>
                                    <containerNamePattern>it-gazelle-user-management-quarkus</containerNamePattern>
                                    <dependsOn>
                                        <image>gazelle-database</image>
                                    </dependsOn>
                                    <network>
                                        <mode>custom</mode>
                                        <name>localit</name>
                                        <alias>gazelle-user-management-quarkus</alias>
                                    </network>
                                    <ports>
                                        <port>8080:8080</port>
                                    </ports>
                                    <volumes>
                                        <bind>
                                            <volume>src/it/resources:/resources</volume>
                                        </bind>
                                    </volumes>
                                    <env>
                                        <QUARKUS_HTTP_PORT>8080</QUARKUS_HTTP_PORT>
                                        <DB_GUM_HOST>gazelle-database</DB_GUM_HOST>
                                        <DB_GUM_PORT>${db.ext.port}</DB_GUM_PORT>
                                        <DB_GUM_USER>${db.ext.username}</DB_GUM_USER>
                                        <DB_GUM_PASSWORD>${db.ext.password}</DB_GUM_PASSWORD>
                                        <DB_GUM_NAME>${db.ext.name}</DB_GUM_NAME>
                                        <DB_TM_HOST>gazelle-database</DB_TM_HOST>
                                        <DB_TM_PORT>${db.ext.port}</DB_TM_PORT>
                                        <DB_TM_USER>${db.ext.username}</DB_TM_USER>
                                        <DB_TM_PASSWORD>${db.ext.password}</DB_TM_PASSWORD>
                                        <DB_TM_NAME>gazelle</DB_TM_NAME>
                                        <SMTP_SSL_ENABLED>false</SMTP_SSL_ENABLED>
                                        <SMTP_MOCK_ENABLED>true</SMTP_MOCK_ENABLED>
                                        <SMTP_USERNAME>test</SMTP_USERNAME>
                                        <SMTP_PASSWORD>test</SMTP_PASSWORD>
                                        <SMTP_PORT>1025</SMTP_PORT>
                                        <SMTP_HOST>mailhog</SMTP_HOST>
                                        <GZL_TM_URL>http://localhost:8080/gazelle</GZL_TM_URL>
                                        <GZL_USER_INACTIVATED_PURGE_AFTER_DAYS>31</GZL_USER_INACTIVATED_PURGE_AFTER_DAYS>
                                        <GZL_JWT_VERIFY_AUDIENCE>http://localhost:8081</GZL_JWT_VERIFY_AUDIENCE>
                                        <ROOT_TEST_BED_URL>http://localhost:8080</ROOT_TEST_BED_URL>
                                        <GZL_GUM_K8S_ID>gazelle-user-management-11111-11111</GZL_GUM_K8S_ID>
                                        <GZL_TERMS_OF_SERVICE_URL>https://termslink.fr</GZL_TERMS_OF_SERVICE_URL>
                                        <GZL_PRIVACY_POLICY_URL>https://privacypolicy.fr</GZL_PRIVACY_POLICY_URL>
                                        <GZL_SERVICE_REGISTRY_ENABLED>false</GZL_SERVICE_REGISTRY_ENABLED>
                                        <GZL_SSO_URL>http://gazelle-user-management-keycloak:28080</GZL_SSO_URL>
                                        <GZL_SSO_ADMIN_USER>gazelle-clients-admin</GZL_SSO_ADMIN_USER>
                                        <GZL_SSO_REALM>gazelle</GZL_SSO_REALM>
                                        <GZL_SSO_ADMIN_PASSWORD>gazelle</GZL_SSO_ADMIN_PASSWORD>
                                        <GZL_M2M_CLIENT_SECRET>secret</GZL_M2M_CLIENT_SECRET>
                                        <JWT_VERIFY_ISSUER>http://gazelle-user-management-keycloak:28080/realms/gazelle</JWT_VERIFY_ISSUER>
                                        <JWT_VERIFY_PUBLIC_KEY_LOCATION>http://gazelle-user-management-keycloak:28080/realms/gazelle/protocol/openid-connect/certs</JWT_VERIFY_PUBLIC_KEY_LOCATION>
                                        <MQTT_HOST>mosquitto</MQTT_HOST>
                                        <MQTT_PORT>1884</MQTT_PORT>
                                        <MQTT_USERNAME>it_user</MQTT_USERNAME>
                                        <MQTT_PASSWORD>it_password</MQTT_PASSWORD>
                                    </env>
                                    <wait>
                                        <healthy>true</healthy>
                                        <time>40000</time>
                                        <exec>
                                            <postStart>/resources/postgres/init_gum.sh</postStart>
                                        </exec>
                                    </wait>
                                </run>
                            </image>
                            <!-- MAILHOG deployment configuration -->
                            <image>
                                <name>mailhog/mailhog</name>
                                <alias>mailhog</alias>
                                <run>
                                    <containerNamePattern>it-mailhog</containerNamePattern>
                                    <network>
                                        <mode>custom</mode>
                                        <name>localit</name>
                                        <alias>mailhog</alias>
                                    </network>
                                    <ports>
                                        <port>8025:8025</port>
                                    </ports>
                                </run>
                            </image>
                            <!-- Mosquitto deployment configuration -->
                            <image>
                                <name>eclipse-mosquitto:2.1.2-alpine</name>
                                <alias>mosquitto</alias>
                                <run>
                                    <containerNamePattern>it-mosquitto</containerNamePattern>
                                    <network>
                                        <mode>custom</mode>
                                        <name>localit</name>
                                        <alias>mosquitto</alias>
                                    </network>
                                    <ports>
                                        <port>1884:1884</port>
                                    </ports>
                                    <entryPoint>
                                        <exec>
                                            <arg>/bin/sh</arg>
                                            <arg>-c</arg>
                                            <arg>sed -i 's/1883/1884/g' /mosquitto-no-auth.conf &amp;&amp; exec /usr/sbin/mosquitto -c /mosquitto-no-auth.conf</arg>
                                        </exec>
                                    </entryPoint>
                                </run>
                            </image>
                        </images>
                    </configuration>
                    <executions>
                        <execution>
                            <id>buildImage</id>
                            <phase>package</phase>
                            <goals>
                                <goal>build</goal>
                            </goals>
                        </execution>
                        <execution>
                            <id>startKeycloak</id>
                            <phase>pre-integration-test</phase>
                            <goals>
                                <goal>start</goal>
                            </goals>
                            <configuration>
                                <skip>${skipITs}</skip>
                            </configuration>
                        </execution>
                        <execution>
                            <id>stopAndRemoveKeycloak</id>
                            <phase>post-integration-test</phase>
                            <goals>
                                <goal>stop</goal>
                            </goals>
                            <configuration>
                                <skip>${skipITs}</skip>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <!-- for integration tests -->
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <configuration>
                        <systemPropertyVariables>
                            <dbExtPort>${db.ext.port}</dbExtPort>
                            <dbExtName>${db.ext.name}</dbExtName>
                            <dbExtUsername>${db.ext.username}</dbExtUsername>
                            <dbExtPassword>${db.ext.password}</dbExtPassword>
                            <dbExtHost>${db.ext.host}</dbExtHost>
                        </systemPropertyVariables>
                        <environmentVariables>
                            <MQTT_HOST>${db.ext.host}</MQTT_HOST>
                        </environmentVariables>
                    </configuration>
                    <executions>
                        <execution>
                            <goals>
                                <goal>integration-test</goal>
                                <goal>verify</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>dev</id>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
    </profiles>

    <repositories>
        <repository>
            <id>IHE</id>
            <name>IHE Public Maven Repository Group</name>
            <url>https://nexus.ihe-catalyst.net/repository/maven-public</url>
            <layout>default</layout>
            <releases>
                <updatePolicy>never</updatePolicy>
            </releases>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>IHE-plugins</id>
            <name>IHE Plugins Public Maven Repository Group</name>
            <url>https://nexus.ihe-catalyst.net/repository/maven-public</url>
            <layout>default</layout>
            <releases>
                <updatePolicy>never</updatePolicy>
            </releases>
        </pluginRepository>
    </pluginRepositories>

    <contributors>
        <contributor>
            <organization>ANS</organization>
            <organizationUrl>https://esante.gouv.fr/</organizationUrl>
        </contributor>
    </contributors>
</project>
