
# Use a random HTTP port during tests to avoid port collisions
quarkus.http.root-path=

# Ensure service metadata binding URL matches the test HTTP port
gzl.service.validation.interface.binding-url=${test.url}${quarkus.http.root-path}/rest
gzl.service.rest.interface.baseUrl=${test.url}${quarkus.http.root-path}/rest
