parent=keycloak
import=common/keycloak

styles=web_modules/@patternfly/react-core/dist/styles/base.css web_modules/@patternfly/react-core/dist/styles/app.css node_modules/patternfly/dist/css/patternfly.min.css node_modules/patternfly/dist/css/patternfly-additions.min.css lib/pficon/pficon.css css/login.css css/tile.css css/gazelle.css

registrationUrl=${env.GZL_USER_MANAGEMENT_FRONT_URL:http://localhost:3000/gazelle/user-management}/registration
SSOLogoUrl=${env.GZL_SSO_LOGO_URL:}
DefaultSSOLogoPath=img/gz_logo.svg