import * as jsonSourceMap from "json-source-map";

/**
 * Finds the line number in a JSON content for a specific JSON path.
 * @param jsonPath - The JSON path (e.g., "$.user.name" or ".user[0].id").
 * @param content - The JSON content as a string.
 * @returns The line number (1-based) where the path points to, or 0 if not found.
 * comment : This function has been generated by AI.
 */
export function findLineNumberFromJsonPath(jsonPath: string, content: string): number {
  try {
    let jsonContent = content;
    try {
      jsonContent = atob(content);
    } catch {
      // If atob fails, assume content is already decoded
    }

    // Parse JSON with source map information
    const result = jsonSourceMap.parse(JSON.stringify(JSON.parse(jsonContent), null, 2));
    const { pointers } = result;

    // Clean up the JSON path for matching
    // Convert various path formats to a normalized format
    const normalizedPath = jsonPath
      .replace(/^\$\.?/, "") // Remove leading $ and optional dot
      .replace(/^\.*/, ""); // Remove any leading dots

    // Find matching pointer
    let bestMatch = "";
    let bestPointer = null;

    // Look for both /${normalizedPath} and /${normalizedPath} in pointers
    for (const [path, pointer] of Object.entries(pointers)) {
      // Check for direct match
      if (path === `/${normalizedPath}` || path === `/${normalizedPath.replaceAll(".", "/")}`) {
        return pointer.value.line + 1; // +1 for 1-based line numbers
      }

      if (normalizedPath.startsWith(path.slice(1).replaceAll("/", ".")) && path.length > bestMatch.length) {
        bestMatch = path;
        bestPointer = pointer;
      }
    }

    if (bestPointer) {
      return bestPointer.value.line + 1; // +1 for 1-based line numbers
    }

    return 0;
  } catch (error) {
    console.error("Error finding line number from JSON path:", error);
    return 0;
  }
}
